packages:
  - packages/*
  - services/linearbot
  - services/slackbotv2
  - services/discordbot
  - services/teamsbot

patchedDependencies:
  '@chat-adapter/linear@4.31.0': patches/@chat-adapter__linear@4.31.0.patch
  '@chat-adapter/discord@4.31.0': patches/@chat-adapter__discord@4.31.0.patch
  '@chat-adapter/slack@4.31.0': patches/@chat-adapter__slack@4.31.0.patch
  '@chat-adapter/state-pg@4.31.0': patches/@chat-adapter__state-pg@4.31.0.patch
