{{- if .Values.repoCache.enabled }}
{{- if and .Values.repoCache.githubToken.token (not .Values.repoCache.githubToken.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "centaur.repoCacheGithubTokenSecretName" . }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "repo-cache") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.repoCache.githubToken.secretKey }}: {{ .Values.repoCache.githubToken.token | quote }}
{{- end }}
{{- end }}
