{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centaur.componentName" (dict "root" . "component" "postgres") }}
  labels:
{{ include "centaur.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  selector:
{{ include "centaur.componentSelectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
{{- end }}
